### ISSUE TITLE
Add a feature to remove admin rights on logout / reboot

### ISSUE THREAD

**Issue by memile123** [sgmills/PrivilegesDemoter#11]
Hi - Thank you for all the work on this tool, its been very helpful in my org. I have noticed admin permissions are still kept after reboot, logout and sleep. Any thoughts around adding something to remove or address?

**Comment by sgmills** [comment]
Thanks for the suggestion! I'm interested in the possibility, but I'm not sure it could be done with how things are set up currently. I'll have to give it some thought.

Feel free to suggest how you might do it and/or submit a PR if you have ideas!

**Comment by Jayyfh** [comment]
You could use PriviligesCLI and trigger it at logout via Jamf. Or you could use a logout hook and a script, but im not sure if this works in the current macOS version.

**Comment by sgmills** [comment]
PrivilegesDemoter version 3 is now in pre-release and there are some options in the [wiki](https://github.com/sgmills/PrivilegesDemoter/wiki) for making demote on login work.
