### ISSUE TITLE
Unable to upload the json 

### ISSUE THREAD

**Issue by mani2care** [sgmills/PrivilegesDemoter#16]
Getting error message unable to upload or create the json 

<img width="910" alt="image" src="https://github.com/sgmills/PrivilegesDemoter/assets/52978899/442469d8-ea8c-4691-a8ea-12b920f20580">

**Comment by sgmills** [comment]
I have validated that the JSON schema works perfectly fine with Jamf Pro 10.48.1. Please ensure you have copied the entire file as formatted here and try again: [https://raw.githubusercontent.com/sgmills/PrivilegesDemoter/main/JSON%20Schema%20-%20PrivilegesDemoter-3.0.json](https://raw.githubusercontent.com/sgmills/PrivilegesDemoter/main/JSON%20Schema%20-%20PrivilegesDemoter-3.0.json)
