### ISSUE TITLE
Multiple Admin Accounts

### ISSUE THREAD

**Issue by jamesp132** [sgmills/PrivilegesDemoter#4]
Hey! 

All is working perfectly I'm just wondering as we use multiple admin accounts (for a old build which is being phased out and a new build is it possible to target both admin accounts?)

Many thanks

**Comment by sgmills** [comment]
Hello! I do not currently have plans to add additional admin accounts to exclude, as that would be largely unnecessary. 

If any given admin account is demoted by the privileges demoter tool you can always elevate that account back to admin with the Privileges application or PrivilegesCLI. The current admin exclusion isn't even really needed, it's just a quality of life thing to remove that extra step of elevating once logged in.
