### ISSUE TITLE
Package a release without IBM Notifier

### ISSUE THREAD

**Issue by Pandemicus** [sgmills/PrivilegesDemoter#6]
We use IBM Notifier but we don't install it in /Applications. We install it in a semi-hidden folder to not clutter our users /Applications folder since they cannot use the app itself anyway.

Could you make pkg in your release page without IBM Notifier?

In your script you could also include a custom variable for the IBM Notifier path? Eg. ibm_notifier_path="${9}"

Thank you in advance! PrivilegesDemoter is a great enhancement of the Privileges application.

**Comment by sgmills** [comment]
This issue has been addressed in v2.1

**Comment by Pandemicus** [comment]
Sorry for the late reply, I'm back from a long parental leave this week. 

Thank you so much for the custom path to IBM Notifier!

It would be super nice if we could have a pkg without IBM Notifier or Privileges also!
